### ISSUE TITLE
Polar SDK: Setup Github-action for NPM package deployment

### ISSUE THREAD

**Issue by emilwidlund** [polarsource/polar#1340]
### What

Setup a Github action which automatically uploads a new version of the Polar SDK when a new Release is created on Github.

### Why

Ensures that we have an automatic deployment strategy to the package registry when new releases are tagged on Github. 

### Example

Read more here: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

```
name: Publish Polar SDK to NPM
on:
  release:
    types: [published]

jobs:
  build:
      name: "SDK: Publish"
      timeout-minutes: 15
      runs-on: ubuntu-22.04
 
      steps:
        - name: Check out code
          uses: actions/checkout@v3
          with:
            fetch-depth: 0 # chromatic requires the full history for it's smartness

        - uses: pnpm/action-setup@v2.2.4
          with:
            version: 8.7.0

        - name: Setup Node.js environment
          uses: actions/setup-node@v3
          with:
            node-version: v18
            cache: 'pnpm'
            cache-dependency-path: 'clients/pnpm-lock.yaml'

        - name: Install dependencies
          working-directory: ./clients
          run: pnpm install

        - name: Publish SDK
          working-directory: ./clients/packages/sdk
          run: pnpm publish
          env:
            NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
```
